export const FETCH_SONGS_INFO_REQUEST = 'FETCH_SONGS_INFO_REQUEST';
export const FETCH_SONGS_INFO_SUCCESS = 'FETCH_SONGS_INFO_SUCCESS';
export const FETCH_SONGS_INFO_ERROR = 'FETCH_SONGS_INFO_ERROR';

export const SELECT_TRACK_TO_PLAY = 'SELECT_TRACK_TO_PLAY';
